version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_USER: devuser
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@alancolant.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres


  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - "9200:9200"
    environment:
      cluster.name: docker-cluster
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms2048m -Xmx8192m"

    healthcheck:
      test: [ "CMD-SHELL","curl http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.1
    environment:
      xpack.security.enabled: false
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - '5601:5601'

volumes:
  postgres-data:
  mysql-data: